pipeline:
  # build:
  #   image: python:3.5.1-alpine
  #   commands:
  #     - pip install --no-cache-dir --upgrade pip setuptools flake8
  #     - flake8 run_marathon.py
  #     - pip install -r requirements.txt

  test:
    image: python:3.5.1-alpine
    marathonfile: testapp/marathon.json
    server: http://localhost:8080
    secrets: [marathon_secret_value, another_secret]
    values: [marathon_secret_value, another_secret]
    environment:
      - PYTHONPATH=/drone/src/app
    commands:
      - pip install -r requirements.txt
      - python test.py

  docker:
    image: plugins/docker
    repo: e20co/drone-marathon
    tag: latest
    secrets: [docker_username, docker_password]
    when:
      branch: drone-0.7
      event: push

  marathon_deploy:
    image: e20co/drone-marathon
    marathonfile: testapp/marathon.json
    server: http://marathon.mesos:8080
    secrets: [marathon_secret_value, another_secret]
    values: [marathon_secret_value, another_secret]
    when:
      branch: drone-0.7
      event: push

# TODO: We need to figure out how to test this package...
# services:
#   marathon:
#     image: mesosphere/marathon:v0.13.0-RC2
