pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools flake8
      - flake8 run_marathon.py
      - pip install -r requirements.txt

  docker:
    image: plugins/docker
    repo: e20co/drone-marathon
    tag: v0.7
    secrets: [docker_username, docker_password]
    when:
      branch: drone-0.7
      event: push

  docker_develop:
    image: plugins/docker
    repo: e20co/drone-marathon
    tag: develop
    secrets: [docker_username, docker_password]
    when:
      branch: develop
      event: push

  marathon_deploy:
    image: e20co/drone-marathon:v0.7
    marathonfile: testapp/marathon.json
    server: http://marathon.mesos:8080
    secrets: [marathon_secret_value]
    when:
      branch: drone-0.7
      event: push

# TODO: We need to figure out how to test this package...
# services:
#   marathon:
#     image: mesosphere/marathon:v0.13.0-RC2
