pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools wheel flake8
      - flake8 run_marathon.py
      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
      # - python test.py

  docker:
    image: plugins/docker
    repo: e20co/drone-marathon
    tag: 0.5
    when:
      branch: drone-0.5
      event: push

# TODO: We need to figure out how to test this package...
# services:
#   marathon:
#     image: mesosphere/marathon:v0.13.0-RC2
